Created tests
humaniverse/loneliness pull request #2
Opened 2023-07-20 14:14 UTC by MatteoLarrode

I used the tinytest package to create tests ran on the loneliness dataset for Scotland at MSOA level (Interzones). 

To make sure the tests were operational, I also created a dummy dataset that fits our expectations of the final dataset. 
This dummy dataset is not meant to stay, but can be used temporarily before the final dataset is added.

_Question_: the dplyr and geographr are necessary to run the tests; do we need to add a dependency to the package?

2023-07-31 15:11 UTC, MikeJohnPage commented
> Question: the dplyr and geographr are necessary to run the tests; do we need to add a dependency to the package?

My answer might change as I make my way through the package but:
- If possible, we should remove these dependencies
- If we have to keep the dependencies, they should be added to the `DESCRIPTION` file.

2023-07-31 16:04 UTC, MikeJohnPage requested changes
Outstanding work!

Please can you review/make the suggested changes. Once complete, I will review/test the GitHub actions workflows.

Thanks 🚀

2023-07-31 16:04 UTC, MikeJohnPage commented on inst/tinytest/test_loneliness_scotland_iz22.R
> +)
Can we replace the dplyr code with a base R equivalent here? Such as:

```r
expect_equal(
  sort(dummy_loneliness_scotland_iz22$iz_code11),
  sort(unique(lookup_dz11_iz11_ltla20$iz11_code))
)
```

2023-07-31 16:04 UTC, MikeJohnPage commented on inst/tinytest/test_loneliness_scotland_iz22.R
> +expect_true(all_within_threshold)
This is brilliant.

2023-07-31 16:04 UTC, MikeJohnPage commented on inst/tinytest/test_loneliness_scotland_iz22.R
> +)
Please can you provide some more context to explain this block of code?

Why does the previous code block not test the ranks adequately?

2023-07-31 16:04 UTC, MikeJohnPage commented on inst/tinytest/test_loneliness_scotland_iz22.R
> +actual_counts <- grouped_deciles$n
Please can we replace this with a base R equivalent? Such as:

```r
as.vector(table(dummy_loneliness_scotland_iz22$deciles))
```
This will allow us to remove the dependency on `dplyr`.

2023-07-31 16:04 UTC, MikeJohnPage commented on inst/tinytest/test_loneliness_scotland_iz22.R
> +  lookup_dz11_iz11_ltla20 |>
This line appears to be the only time the `geographr` is called. Considering the package isn't yet released to CRAN, isn't stable, and is large, it doesn't make sense to add a dependency to the package, if avoidable.

Instead, can we store a list of IZ codes somewhere, and read those in, instead? We could place these in `inst/extdata/` for example.

2023-07-31 16:05 UTC, MikeJohnPage commented on inst/tinytest/test_loneliness_scotland_iz22.R
> +library(dplyr)
Please remove (see below)

2023-08-01 12:25 UTC, MatteoLarrode commented on inst/tinytest/test_loneliness_scotland_iz22.R
> +)
`expect_equal(
   sort(dummy_loneliness_scotland_iz22$rank),
   1:1279
 )`

assumes that each IZ was attributed a unique rank. However, the ranking method used handles ties by averaging the ranks. So in the (unlikely) case where two IZ's are tied, this method would throw an error. 

The idea is to compute the expected ranks with the loneliness z-score, using the correct tie handling method, and to compare them with actual ranks. 

I will remove the first block of code.

2023-08-01 15:48 UTC, merged