England Loneliness 2020/21 from the Community Life Survey
humaniverse/loneliness pull request #3
Opened 2023-07-21 15:26 UTC by jennajt

- Added notebook and csv using the Community Life Survey
- Mapped from Output Area Classification to LSOA

2023-07-28 13:32 UTC, MikeJohnPage commented
In the notebook, you replace missing values with zero like so:

<img width="883" alt="Screenshot 2023-07-28 at 15 20 23" src="https://github.com/humaniverse/loneliness/assets/38110953/38eef7f9-c476-4c3d-8356-6d7e439b0db8">

This creates a cluster of points around zero, which weren't previously present in the data.

<img width="893" alt="Screenshot 2023-07-28 at 15 26 07" src="https://github.com/humaniverse/loneliness/assets/38110953/3cb7634c-37db-44cc-bf6a-7afea28518e5">

If we look at the notes in the raw data for why there are `NA` values present for this data it says:

> Where the total number of responses is less than 30, this data has been suppressed.

This means we do not know the true values of the missing data. I would argue that replacing them with zero distorts the data in a negative way. Better, to leave them as missing, or impute a value.

2023-07-28 13:53 UTC, MikeJohnPage commented
In this step when you select the cols `lsoa11_code` and `oa11_code`, you need to take the distinct values as they are repeated many times due to the different postcodes:

<img width="895" alt="Screenshot 2023-07-28 at 15 51 47" src="https://github.com/humaniverse/loneliness/assets/38110953/681b57a0-ad94-41bd-830b-9f7128ca5d60">

The averaging performed in a later step should cancel out these repeat values, but it makes it harder to follow as-is.

2023-07-28 14:30 UTC, MikeJohnPage commented
I think something has gone wrong here. The number of 2011 LSOA's in England should be 32,844, not 41,729. It looks like you have retained data for the devolved nations:

<img width="689" alt="Screenshot 2023-07-28 at 16 28 53" src="https://github.com/humaniverse/loneliness/assets/38110953/c5552896-edac-497b-8b36-9824c20dea18">

2023-07-28 14:33 UTC, MikeJohnPage commented
The file `../../extdata/lookup_21.feather` doesn't exist in the repo and should be shared:

<img width="728" alt="Screenshot 2023-07-28 at 16 32 17" src="https://github.com/humaniverse/loneliness/assets/38110953/75cd0be3-d6d9-4c27-8f64-88e50722e1aa">

2023-07-28 14:37 UTC, MikeJohnPage commented
Unfortunately, this approach isn't valid. This is because it assumes LSOA's are in a 1:1 relationship from 2011 to 2021, which is not true. See [this](https://github.com/britishredcrosssociety/health-inequalities-explorer/pull/50#issuecomment-1653959140) comment in a HIE PR which explains this problem in more detail and the solution that needs to be taken.

<img width="885" alt="Screenshot 2023-07-28 at 16 36 43" src="https://github.com/humaniverse/loneliness/assets/38110953/375d2b36-3a3e-4597-8178-e9713c42805a">

2023-07-28 15:27 UTC, MikeJohnPage requested changes

2023-07-28 15:27 UTC, MikeJohnPage commented on .gitignore
> +oac_lookup.csv
Without access to these temporary files, I am unable to replicate your analysis. Can we not add these into `inst/` somewhere?

2023-07-28 15:31 UTC, MikeJohnPage commented
Thanks for all your hard work on this, it is appreciated. I've left you comments / things to change above. I had bit of a hard time reasoning about some of the Python code, so I replicated the analysis in R to follow along as I was doing the review, fixing a few of the issues I have described above (e.g., not replacing the missing values with zero, keeping England only LSOA's). I added a file with this R code to this branch [here](https://github.com/humaniverse/loneliness/blob/england_cls/inst/python/notebooks/england_2021.R). Feel free to build off this for the LSOA aggregations if helpful or continue making the changes in the notebook.

Thanks 😃

2023-08-14 15:22 UTC, jennajt commented
Your comments above have been addressed. In addition I restructured the repo to make the code reproducible:

-  The main script to review is `cls_england_2020.py `. It contains everything needed to download all the files and process the script to produce a csv. Note this script calls an R script. I haven't added an R environment for it, let me know if you think it is required.
- The notebook is not for reviewing - it is where the experimentation is done.
- I've created a `requirements.txt` document to manage python dependencies. You will need to create your own virtual env and install the libraries and versions, instructions in `README.md`
- I've created an RDA file and some basic documentation for the dataset.

2023-08-15 14:30 UTC, MikeJohnPage commented
Amazing work. Merging now. 🚀

2023-08-15 14:41 UTC, merged