Scotland 2022
humaniverse/loneliness pull request #4
Opened 2023-07-21 15:27 UTC by jennajt

- The Scotland csv has been updated using the inverse distance weighted method
- Please review the two notebooks and csv only, other files have note been updated since the initial commit

2023-08-03 09:47 UTC, MikeJohnPage requested changes
Hey, before I get round to `idw-mapping-scotland.ipynb`, please can you take a look at the feedback/changes I've left in `clinical-scotland-2022.ipynb`. The changes in to this file will effect the rest of the analyses. Thanks :)

2023-08-03 09:47 UTC, MikeJohnPage commented on inst/python/notebooks/clinical-scotland-2022.ipynb
<img width="1170" alt="Screenshot 2023-08-03 at 10 18 28" src="https://github.com/humaniverse/loneliness/assets/38110953/ab10b492-7042-4c71-9280-5353be1a568d">

Why did you separately specify col names and not just include them in the subsequent function call directly: 

<img width="1154" alt="Screenshot 2023-08-03 at 10 19 33" src="https://github.com/humaniverse/loneliness/assets/38110953/cbf180b7-d347-4e3e-83b6-4dd0af05ae7c">

2023-08-03 09:47 UTC, MikeJohnPage commented on inst/python/notebooks/clinical-scotland-2022.ipynb
The `\\` in `prescriptions_scotland\\` is Windows specific and causes the cell to fail when executed on a unix based machine. Can we not use the general `/`, used in the other file path names here too?
<img width="883" alt="Screenshot 2023-08-03 at 10 55 35" src="https://github.com/humaniverse/loneliness/assets/38110953/aff87b26-97d9-43da-b081-4ff3714dfbbc">

2023-08-03 09:47 UTC, MikeJohnPage commented on inst/python/notebooks/clinical-scotland-2022.ipynb
Please can we try and use more descriptive names? So far we have:

- `data`
- `monthly_data`
- `processed_data`

Trying to keep track of these names when going back and forth in the code is difficult. More descriptive names might be:

- `monthly_prescriptions`
- `monthly_prescriptions_loneliness_counts`

etc.

2023-08-03 09:47 UTC, MikeJohnPage commented on inst/python/notebooks/clinical-scotland-2022.ipynb
This strategy calls `drop_duplicates` twice. In the second call, after the data has been joined to GP data, are we not just removing repeat observations from the prescription data (called `data` here)? If so, why is there repeat prescription data, and should this not be taken care of above, rather than here?

<img width="1087" alt="Screenshot 2023-08-03 at 11 14 49" src="https://github.com/humaniverse/loneliness/assets/38110953/b89f2492-26a7-434c-ae98-0047020d9780">

2023-08-03 09:47 UTC, MikeJohnPage commented on inst/python/notebooks/clinical-scotland-2022.ipynb
Why do so many GP's not have geographic data? Have you done a deep dive into the docs? Are the data missing at random? If not, how can we control for this?

<img width="1106" alt="Screenshot 2023-08-03 at 11 20 01" src="https://github.com/humaniverse/loneliness/assets/38110953/f328c003-a294-4c40-805d-cfe3f8bd00df">

2023-08-03 09:47 UTC, MikeJohnPage commented on inst/python/notebooks/clinical-scotland-2022.ipynb
I just did a little exploration of the GP practice data in R, and it appears there are no missing postcodes. For example, we can see below that the `n_missing` value for postcodes is zero:

```r
> library(tidyverse)

> jan <- read_csv("inst/extdata/gp_data/practice_contactdetails_jan2022.csv")
> apr <- read_csv("inst/extdata/gp_data/practice_contactdetails_apr2022-open-data.csv")
> jul <- read_csv("inst/extdata/gp_data/practice_contactdetails_jul2022-open-data.csv")
> oct <- read_csv("inst/extdata/gp_data/practice_contactdetails_oct2022-open-data.csv")


> bind_rows(jan, apr, jul, oct) |> 
+   skimr::skim()
── Data Summary ────────────────────────
                           Values                      
Name                       bind_rows(jan, apr, jul, ...
Number of rows             3663                        
Number of columns          15                          
_______________________                                
Column type frequency:                                 
  character                13                          
  numeric                  2                           
________________________                               
Group variables            None                        

── Variable type: character ────────────────────────────────────────────────────
   skim_variable   n_missing complete_rate min max empty n_unique whitespace
 1 GPPracticeName          0         1       9  92     0      951          0
 2 AddressLine1            0         1       9  58     0      952          0
 3 AddressLine2            7         0.998   4  50     0      719          0
 4 AddressLine3           32         0.991   3  38     0      560          0
 5 AddressLine4          982         0.732   3  27     0      253          0
 6 Postcode                0         1       6   8     0      739          0
 7 TelephoneNumber        66         0.982  13  18     0      917          0
 8 PracticeType            0         1       2   3     0        3          0
 9 Dispensing              0         1       1   1     0        2          0
10 HB                      0         1       9   9     0       14          0
11 HSCP                    0         1       9   9     0       31          0
12 DataZone                0         1       9   9     0      688          0
13 GPCluster               1         1.00    4  40     0      153          0

── Variable type: numeric ──────────────────────────────────────────────────────
  skim_variable    n_missing complete_rate   mean     sd    p0   p25   p50
1 PracticeCode             0             1 50301. 23699. 10002 30280 49801
2 PracticeListSize         0             1  6407.  4176.     0  3545  5962
     p75  p100 hist 
1 70662  90204 ▇▅▇▆▇
2  8676. 56004 ▇▁▁▁▁
```
Has something gone wrong with one of your `merge` statements, or am I mistaking something?

2023-08-03 09:47 UTC, MikeJohnPage commented on inst/python/notebooks/clinical-scotland-2022.ipynb
Are we able to handle these two edge cases now, e.g., by assigning the loneliness levels equally between them? Have you managed to go a quick search to discover why they repeat?

<img width="930" alt="Screenshot 2023-08-03 at 11 37 57" src="https://github.com/humaniverse/loneliness/assets/38110953/a201ebdc-c502-4e46-96d1-fef37c069fb7">

2023-08-03 09:47 UTC, MikeJohnPage commented on inst/python/notebooks/clinical-scotland-2022.ipynb
This cell is throwing an error due to conflicting col names. I've followed the notebook in sequence.

Both the colnames `Postcode` and `BNFItemDescription` no longer exists in the data that is read in the previous cells.

<img width="1078" alt="Screenshot 2023-08-03 at 11 42 38" src="https://github.com/humaniverse/loneliness/assets/38110953/b99bf979-12b8-4122-923c-8e81a54c73b0">

2023-08-03 13:00 UTC, jennajt commented on inst/python/notebooks/clinical-scotland-2022.ipynb
This was in the original code - presume it is because this notebook is replicated across the nations and rather than changing the function below that variable is changed.

2023-08-03 16:41 UTC, jennajt commented on inst/python/notebooks/clinical-scotland-2022.ipynb
Good spot. The second round of `drop_duplicates()` should not have found any duplicates. It does indeed stem from duplicates in 'data' which are the prescription in the community files. 

There were only 7 duplicate entries (out of 13k) in the second round of  `drop_duplicates()`  . I've now handled it higher up in the notebook when the prescription in the community files are  being merged.

2023-08-04 08:57 UTC, jennajt commented on inst/python/notebooks/clinical-scotland-2022.ipynb
Good spot

- The missing postcodes are because the GPPractice codes in the prescription table do not exist in the GP Practice contact details table. This explains why there are no missing postcodes when you looked at the GP Practice contact details table.
- The prescription data is defined as "information on community pharmacy activity and direct pharmaceutical care services for all NHS health boards". In the original code, GPPractice codes from the prescription data were subsetted from the GP contact details sheet with a comment "GP Practices only". I didn't understand why that was done, so I omitted it. Now upon reflection, I'm guessing that despite the column heading being called "GPPractice", it probably include other types of practices (e.g. pharmacies). This would explain why so many did not match and why the original code was subsetted. 
- I've amended inline with the original code

2023-08-04 10:20 UTC, jennajt commented on inst/python/notebooks/clinical-scotland-2022.ipynb
I've deleted second instance of them so we aren't double counting . Hard to know whether its because the GP has moved, or its an error in data.

2023-08-07 15:54 UTC, MikeJohnPage commented on inst/python/notebooks/clinical-scotland-2022.ipynb
Where can the GP reference details be found? How hard would it be to implement this?

<img width="1807" alt="Screenshot 2023-08-07 at 16 42 31" src="https://github.com/humaniverse/loneliness/assets/38110953/06640805-68bd-4149-acfa-3668e45c3aa8">

It seems a good compromise strategy might be to take the latest value for the postcode. As it stands I think the code is doing this by taking the first value for each GP practice, but this is contingent on the data sets being read in from newest to oldest before being merged. Is there a way to make this process more robust, should the naming of the files change and this reading order not be followed as intended?

2023-08-07 15:54 UTC, MikeJohnPage commented on inst/python/notebooks/idw-mapping-scotland.ipynb
As was done in `clinical-scotland-2022.ipynb`, please can we use more descriptive variables name in place of names such as `df` (which tend to be hard to track and understand).

<img width="683" alt="Screenshot 2023-08-07 at 17 18 53" src="https://github.com/humaniverse/loneliness/assets/38110953/6c101eb3-6ada-4542-9741-4d9c146f36ff">

2023-08-07 15:54 UTC, MikeJohnPage commented on inst/python/notebooks/idw-mapping-scotland.ipynb
I can't get this cell to run without erroring. Could this be due to different version numbers? This does warrant implementing a virtual environment to ensure reproducibility across machines?

<img width="1195" alt="Screenshot 2023-08-07 at 17 49 55" src="https://github.com/humaniverse/loneliness/assets/38110953/6c563f01-6701-4bc8-90d1-cb83aa3e7c74">

2023-08-18 07:57 UTC, closed without merging